In [ ]:
import numpy as np

In [ ]:
array_1d = np.array([1, 2, 3, 4, 5])
print(array_1d)
print(array_1d.shape)

[1 2 3 4 5]
(5,)


In [ ]:
array_2d = np.array([[1, 2], [3, 4],[5, 6]])
print(array_2d)
print(f"shape of the array is {array_2d.shape}")

[[1 2]
 [3 4]
 [5 6]]
shape of the array is (3, 2)


In [ ]:
# Zeros numpy
zeros_1d = np.zeros(5)
zeros_1d

array([0., 0., 0., 0., 0.])

In [ ]:
zeros_2d = np.zeros((3,4), dtype=int)
zeros_2d

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
ones_1d = np.ones(5)
ones_2d = np.ones((5,4))

In [ ]:
ones_1d

array([1., 1., 1., 1., 1.])

In [ ]:
ones_2d

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
rand_values = np.random.rand(5)

In [ ]:
rand_values

array([0.14526997, 0.54535252, 0.79531188, 0.20023513, 0.12533569])

In [ ]:
rand_values = np.random.rand(3,3)

In [ ]:
rand_values

array([[0.02350715, 0.66167769, 0.23726598],
       [0.38606375, 0.27286489, 0.19540189],
       [0.23748196, 0.32981928, 0.79059134]])